spring:
  application:
    name: rate-limiter
  redis:
    host: localhost   # Redis server hostname
    port: 6379        # Default Redis port

server:
  port: 8080
  servlet:
    context-path: /api

codeavatar:
  ratelimiter:
    dailyBucket:
      prefix: bucket:daily
